import { createHash } from "node:crypto";
import { lstat, mkdir, open, readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

import { createKJOfficialSettlementFromGamma, type GammaResolutionInput } from "../core/src/adapters/settlement/gamma-resolution.js";
import { fetchPublicMarketBySlug, type PublicBtcFiveMinuteMarket } from "../core/src/adapters/market-data/public-sources.js";
import type { KJOfficialSettlement, KJPaperStrategy } from "../core/src/runtime/kj-paper-engine.js";
import type { PaperSettlementV1, PaperToken } from "../paper-simulation/index.js";
import type { KJExecutionAccountsV1 } from "./kj-execution-coordinator.js";
import type { PaperSessionService } from "./service.js";

export type OfficialMarketBindingV1 = Readonly<{ schemaVersion:"official-market-binding-v1";marketId:string;conditionId:string;slug:string;intervalStart:string;intervalEnd:string;upTokenId:string;downTokenId:string }>;
export type OfficialPaperSettlementLinkV1 = Readonly<{ schemaVersion:"official-paper-settlement-link-v1";identity:string;evidenceFingerprint:string;binding:OfficialMarketBindingV1;official:KJOfficialSettlement;winningToken:PaperToken;state:"PENDING"|"APPLIED";results:Readonly<Partial<Record<KJPaperStrategy,PaperSettlementV1>>>;updatedAtUtc:string }>;
export type OfficialPaperSettlementRecordV1 = Readonly<{ schemaVersion:"official-paper-settlement-record-v1";sequence:string;previousRecordHash:string|null;link:OfficialPaperSettlementLinkV1;recordHash:string }>;
export interface OfficialPaperSettlementStore { load():Promise<readonly OfficialPaperSettlementRecordV1[]>;append(record:OfficialPaperSettlementRecordV1):Promise<void>; }
export interface PublicGammaResolutionSource { readonly source:"PUBLIC_GAMMA";readonly access:"READ_ONLY";fetch(slug:string):Promise<Readonly<{responseStatus:number;rawPayload:string;receiveTime:string}>>; }

const SAFE=/^[a-zA-Z0-9][a-zA-Z0-9._:-]{0,127}$/u;
function stable(value:unknown):string { if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(",")}}`; }
function hash(value:string):string{return createHash("sha256").update(value,"utf8").digest("hex");}
function recordHash(value:Omit<OfficialPaperSettlementRecordV1,"recordHash">):string{return hash(stable(value));}
function utc(value:string,field:string):void{if(!value.endsWith("Z")||!Number.isFinite(Date.parse(value))||new Date(Date.parse(value)).toISOString()!==value)throw new Error(`${field} must be UTC ISO 8601`);}
function binding(market:PublicBtcFiveMinuteMarket):OfficialMarketBindingV1{return Object.freeze({schemaVersion:"official-market-binding-v1",marketId:market.marketId,conditionId:market.conditionId,slug:market.slug,intervalStart:market.intervalStart,intervalEnd:market.intervalEnd,upTokenId:market.upTokenId,downTokenId:market.downTokenId});}

export class DefaultPublicGammaResolutionSource implements PublicGammaResolutionSource {
  readonly source="PUBLIC_GAMMA" as const;readonly access="READ_ONLY" as const;
  async fetch(slug:string){const response=await fetchPublicMarketBySlug(slug,{timeoutMilliseconds:10_000,maxResponseBytes:2*1024*1024});return Object.freeze({responseStatus:response.status,rawPayload:response.rawPayload,receiveTime:response.receiveTime});}
}

export class InMemoryOfficialPaperSettlementStore implements OfficialPaperSettlementStore {
  readonly records:OfficialPaperSettlementRecordV1[]=[];
  async load(){return structuredClone(this.records);}
  async append(record:OfficialPaperSettlementRecordV1){this.records.push(structuredClone(record));}
}

export class FileOfficialPaperSettlementStore implements OfficialPaperSettlementStore {
  readonly #path:string;
  constructor(dataRoot:string){this.#path=join(resolve(dataRoot),"workbench","paper-sessions","kj-official-settlement-links.jsonl");}
  async load():Promise<readonly OfficialPaperSettlementRecordV1[]>{try{const state=await lstat(this.#path);if(state.isSymbolicLink()||!state.isFile())throw new Error("official settlement outbox must be a regular file");const text=await readFile(this.#path,"utf8");return Object.freeze(text.split("\n").filter((line)=>line.trim()!=="").map((line,index)=>{try{return JSON.parse(line) as OfficialPaperSettlementRecordV1;}catch(error){throw new Error(`official settlement outbox line ${index+1} is invalid`,{cause:error});}}));}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return Object.freeze([]);throw error;}}
  async append(record:OfficialPaperSettlementRecordV1):Promise<void>{await mkdir(dirname(this.#path),{recursive:true,mode:0o700});const state=await lstat(this.#path).catch((error:NodeJS.ErrnoException)=>error.code==="ENOENT"?null:Promise.reject(error));if(state?.isSymbolicLink())throw new Error("official settlement outbox must not be a symlink");const handle=await open(this.#path,"a",0o600);try{await handle.writeFile(`${JSON.stringify(record)}\n`,"utf8");await handle.sync();}finally{await handle.close();}}
}

export class OfficialGammaPaperSettlementCoordinator {
  readonly #paper:PaperSessionService;readonly #store:OfficialPaperSettlementStore;readonly #accounts:KJExecutionAccountsV1;readonly #source:PublicGammaResolutionSource;
  readonly #links=new Map<string,OfficialPaperSettlementLinkV1>();#count=0;#last:string|null=null;#initialized=false;#tail:Promise<void>=Promise.resolve();
  constructor(paper:PaperSessionService,store:OfficialPaperSettlementStore,accounts:KJExecutionAccountsV1,source:PublicGammaResolutionSource=new DefaultPublicGammaResolutionSource()){if(accounts.J_FEE_AWARE===accounts.K_DUAL_VOL||!SAFE.test(accounts.J_FEE_AWARE)||!SAFE.test(accounts.K_DUAL_VOL))throw new Error("official settlement requires distinct canonical J/K sessions");if(source.source!=="PUBLIC_GAMMA"||source.access!=="READ_ONLY")throw new Error("official settlement requires read-only public Gamma source");this.#paper=paper;this.#store=store;this.#accounts=Object.freeze({...accounts});this.#source=source;}
  async initialize():Promise<void>{if(this.#initialized)return;for(const record of await this.#store.load())this.#recover(record);this.#initialized=true;for(const link of this.#links.values())if(link.state==="PENDING")await this.#apply(link);}
  links():readonly OfficialPaperSettlementLinkV1[]{return Object.freeze([...this.#links.values()].sort((a,b)=>a.identity.localeCompare(b.identity)));}
  async settleFromPublicGamma(expectedMarket:PublicBtcFiveMinuteMarket,explicitNetworkApproval:true):Promise<OfficialPaperSettlementLinkV1>{if(explicitNetworkApproval!==true)throw new Error("explicit public Gamma network approval is required");const prior=this.#links.get(expectedMarket.marketId);if(prior?.state==="APPLIED")return prior;const response=await this.#source.fetch(expectedMarket.slug);return this.applyGamma({expectedMarket,...response});}
  applyGamma(input:GammaResolutionInput):Promise<OfficialPaperSettlementLinkV1>{let output:OfficialPaperSettlementLinkV1|undefined;const operation=this.#tail.then(async()=>{output=await this.#applyGamma(input);});this.#tail=operation.then(()=>undefined,()=>undefined);return operation.then(()=>output!);}
  async #applyGamma(input:GammaResolutionInput):Promise<OfficialPaperSettlementLinkV1>{if(!this.#initialized)throw new Error("official settlement coordinator is not initialized");const official=createKJOfficialSettlementFromGamma(input);const bound=binding(input.expectedMarket);const winningToken:PaperToken=official.winner==="UP"?"YES":"NO";const evidenceFingerprint=hash(stable({binding:bound,official,winningToken}));const existing=this.#links.get(bound.marketId);if(existing!==undefined){if(existing.evidenceFingerprint!==evidenceFingerprint)throw new Error("official Gamma settlement conflicts with the recorded market evidence");return existing.state==="PENDING"?this.#apply(existing):existing;}const link:OfficialPaperSettlementLinkV1=Object.freeze({schemaVersion:"official-paper-settlement-link-v1",identity:bound.marketId,evidenceFingerprint,binding:bound,official,winningToken,state:"PENDING",results:Object.freeze({}),updatedAtUtc:official.settlementTime});await this.#append(link);this.#links.set(link.identity,link);return this.#apply(link);}
  async #apply(link:OfficialPaperSettlementLinkV1):Promise<OfficialPaperSettlementLinkV1>{const results:Partial<Record<KJPaperStrategy,PaperSettlementV1>>={...link.results};for(const strategy of ["J_FEE_AWARE","K_DUAL_VOL"] as const){const result=results[strategy]??await this.#paper.settleMarket(this.#accounts[strategy],link.binding.marketId,link.winningToken,link.official.settlementTime);if(result.marketId!==link.binding.marketId||result.winningToken!==link.winningToken||result.settledAtUtc!==link.official.settlementTime)throw new Error("pre-existing Paper settlement cannot masquerade as this official Gamma evidence");results[strategy]=result;}const applied:OfficialPaperSettlementLinkV1=Object.freeze({...link,state:"APPLIED",results:Object.freeze(results)});await this.#append(applied);this.#links.set(applied.identity,applied);return applied;}
  async #append(link:OfficialPaperSettlementLinkV1):Promise<void>{const core=Object.freeze({schemaVersion:"official-paper-settlement-record-v1" as const,sequence:String(this.#count),previousRecordHash:this.#last,link});const record=Object.freeze({...core,recordHash:recordHash(core)});await this.#store.append(record);this.#count+=1;this.#last=record.recordHash;}
  #recover(record:OfficialPaperSettlementRecordV1):void{if(record.schemaVersion!=="official-paper-settlement-record-v1"||record.sequence!==String(this.#count)||record.previousRecordHash!==this.#last||Object.keys(record).sort().join(",")!=="link,previousRecordHash,recordHash,schemaVersion,sequence")throw new Error("official settlement outbox chain is invalid");const {recordHash:supplied,...core}=record;if(!/^[a-f0-9]{64}$/u.test(supplied)||recordHash(core)!==supplied)throw new Error("official settlement outbox hash mismatch");this.#validateLink(record.link);const prior=this.#links.get(record.link.identity);if(prior===undefined&&record.link.state!=="PENDING")throw new Error("official settlement terminal record lacks PENDING");if(prior!==undefined&&(prior.evidenceFingerprint!==record.link.evidenceFingerprint||prior.state==="APPLIED"))throw new Error("official settlement outbox contains conflicting or post-terminal evidence");this.#links.set(record.link.identity,Object.freeze(structuredClone(record.link)));this.#count+=1;this.#last=supplied;}
  #validateLink(link:OfficialPaperSettlementLinkV1):void{const b=link.binding;const slug=/^btc-updown-5m-([1-9][0-9]{9})$/u.exec(b.slug);if(link.schemaVersion!=="official-paper-settlement-link-v1"||b.schemaVersion!=="official-market-binding-v1"||link.identity!==b.marketId||!SAFE.test(b.marketId)||!/^0x[0-9a-fA-F]{64}$/u.test(b.conditionId)||slug===null||!/^[0-9]+$/u.test(b.upTokenId)||!/^[0-9]+$/u.test(b.downTokenId)||b.upTokenId===b.downTokenId)throw new Error("official settlement link binding is invalid");utc(b.intervalStart,"binding.intervalStart");utc(b.intervalEnd,"binding.intervalEnd");utc(link.updatedAtUtc,"link.updatedAtUtc");const slugEpoch=Number(slug[1]);if(!Number.isSafeInteger(slugEpoch)||slugEpoch%300!==0||Date.parse(b.intervalStart)!==slugEpoch*1000||Date.parse(b.intervalEnd)-Date.parse(b.intervalStart)!==300_000||Date.parse(link.official.settlementTime)<=Date.parse(b.intervalEnd)||link.official.marketId!==b.marketId||link.official.evidenceStatus!=="OFFICIAL_RESOLUTION"||!/^[a-f0-9]{64}$/u.test(link.official.settlementId)||link.official.evidenceReference!==`gamma-market-by-slug:${b.slug}:${link.official.evidenceReference.split(":").slice(-2).join(":")}`||!/sha256:[a-f0-9]{64}$/u.test(link.official.evidenceReference)||link.winningToken!==(link.official.winner==="UP"?"YES":"NO"))throw new Error("official settlement evidence conflicts with its market binding");if(hash(stable({binding:b,official:link.official,winningToken:link.winningToken}))!==link.evidenceFingerprint)throw new Error("official settlement evidence fingerprint mismatch");const keys=Object.keys(link.results);if(link.state==="PENDING"&&keys.length!==0)throw new Error("pending official settlement has results");if(link.state==="APPLIED"&&(!keys.includes("J_FEE_AWARE")||!keys.includes("K_DUAL_VOL")))throw new Error("applied official settlement lacks canonical results");for(const result of Object.values(link.results)){if(result===undefined)continue;utc(result.settledAtUtc,"canonical settlement time");if(result.marketId!==b.marketId||result.winningToken!==link.winningToken||result.settledAtUtc!==link.official.settlementTime)throw new Error("canonical Paper result conflicts with official settlement evidence");}}
}
