import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import type { PublicBtcFiveMinuteMarket } from "../core/src/adapters/market-data/public-sources.js";
import { GammaResolutionPending } from "../core/src/adapters/settlement/gamma-resolution.js";
import { InMemoryOfficialPaperSettlementStore, InMemoryPaperSessionStateStore, OfficialGammaPaperSettlementCoordinator, PaperSessionService, type CallerManagedPublicMarketAdapter, type OfficialPaperSettlementRecordV1, type OfficialPaperSettlementStore, type PublicGammaResolutionSource } from "../paper-session/index.js";
import type { PaperMarketSnapshotV1, PaperRiskConfigV1 } from "../paper-simulation/index.js";

const root=new URL("../../../",import.meta.url);const receiveTime="2026-07-17T00:05:53.000Z";
const market:PublicBtcFiveMinuteMarket={marketId:"golden-market-1",conditionId:`0x${"a".repeat(64)}`,slug:"btc-updown-5m-1784246400",intervalStart:"2026-07-17T00:00:00.000Z",intervalEnd:"2026-07-17T00:05:00.000Z",upTokenId:"111",downTokenId:"222",active:true,closed:false,acceptingOrders:true,collectible:true,takerFeeRate:"0.07",rawPayload:"{}"};
const snapshot:PaperMarketSnapshotV1={schemaVersion:"paper-market-snapshot-v1",marketId:market.marketId,observedAtUtc:"2026-07-17T00:04:59.800Z",receivedAtUtc:"2026-07-17T00:04:59.900Z",eligible:true,yesAsks:[{price:"0.5",quantity:"2"}],noAsks:[{price:"0.5",quantity:"2"}]};
const risk:PaperRiskConfigV1={schemaVersion:"paper-risk-config-v1",maximumQuoteAgeMs:1000,minimumNetEdge:"0.01",maximumOrderNotional:"100",maximumMarketExposure:"100",maximumTotalExposure:"100"};
const accounts={J_FEE_AWARE:"official-j",K_DUAL_VOL:"official-k"} as const;
function adapter():CallerManagedPublicMarketAdapter{return{adapterId:"official-adapter",source:"PUBLIC_MARKET_DATA",lifecycle:"CALLER_MANAGED",isReady:()=>true,latest:(id)=>id===market.marketId?snapshot:null};}
async function paper(store=new InMemoryPaperSessionStateStore()){const service=new PaperSessionService(adapter(),store);await service.initialize();for(const sessionId of Object.values(accounts))if(await store.loadSession(sessionId)===null)await service.start({schemaVersion:"paper-session-start-v1",sessionId,initialCash:"100",risk,startedAtUtc:"2026-07-17T00:00:01.000Z"});return{service,store};}
async function fixture(){return readFile(new URL("data/fixtures/batch-06/gamma-resolved-market.json",root),"utf8");}
class FakeGamma implements PublicGammaResolutionSource{readonly source="PUBLIC_GAMMA" as const;readonly access="READ_ONLY" as const;calls=0;constructor(readonly payload:string){}async fetch(slug:string){this.calls+=1;assert.equal(slug,market.slug);return{responseStatus:200,rawPayload:this.payload,receiveTime};}}

test("official Gamma evidence settles both canonical J/K sessions and is idempotent",async()=>{const {service}=await paper();const store=new InMemoryOfficialPaperSettlementStore();const source=new FakeGamma(await fixture());const coordinator=new OfficialGammaPaperSettlementCoordinator(service,store,accounts,source);await coordinator.initialize();const first=await coordinator.settleFromPublicGamma(market,true);assert.equal(first.state,"APPLIED");assert.equal(first.winningToken,"YES");assert.equal(first.official.evidenceStatus,"OFFICIAL_RESOLUTION");assert.equal((await service.detail(accounts.J_FEE_AWARE)).settlements.length,1);assert.equal((await service.detail(accounts.K_DUAL_VOL)).settlements.length,1);const replay=await coordinator.settleFromPublicGamma(market,true);assert.equal(replay.evidenceFingerprint,first.evidenceFingerprint);assert.equal(source.calls,1);assert.equal(store.records.length,2);assert.equal(store.records[1]?.previousRecordHash,store.records[0]?.recordHash);});

test("no network approval performs no Gamma request",async()=>{const {service}=await paper();const source=new FakeGamma(await fixture());const coordinator=new OfficialGammaPaperSettlementCoordinator(service,new InMemoryOfficialPaperSettlementStore(),accounts,source);await coordinator.initialize();await assert.rejects(coordinator.settleFromPublicGamma(market,false as true),/explicit public Gamma network approval/u);assert.equal(source.calls,0);assert.equal((await service.detail(accounts.J_FEE_AWARE)).settlements.length,0);});

test("pending, ambiguous, and identity-conflicting Gamma evidence fails closed before Paper settlement",async()=>{const raw=await fixture();const base=JSON.parse(raw) as Record<string,unknown>;for(const [payload,error] of [[{...base,umaResolutionStatus:"proposed"},GammaResolutionPending],[{...base,outcomePrices:'["1", "1"]'},Error],[{...base,conditionId:`0x${"b".repeat(64)}`},Error]] as const){const {service}=await paper();const coordinator=new OfficialGammaPaperSettlementCoordinator(service,new InMemoryOfficialPaperSettlementStore(),accounts,new FakeGamma(JSON.stringify(payload)));await coordinator.initialize();await assert.rejects(coordinator.settleFromPublicGamma(market,true),error);assert.equal((await service.detail(accounts.J_FEE_AWARE)).settlements.length,0);assert.equal((await service.detail(accounts.K_DUAL_VOL)).settlements.length,0);}});

class FailTerminalStore implements OfficialPaperSettlementStore{readonly records:OfficialPaperSettlementRecordV1[]=[];attempt=0;async load(){return structuredClone(this.records);}async append(record:OfficialPaperSettlementRecordV1){this.attempt+=1;if(this.attempt===2)throw new Error("injected official terminal append failure");this.records.push(structuredClone(record));}}
test("pending official evidence recovers idempotently after Paper settlement but before terminal acknowledgement",async()=>{const state=new InMemoryPaperSessionStateStore();const first=await paper(state);const outbox=new FailTerminalStore();const crashed=new OfficialGammaPaperSettlementCoordinator(first.service,outbox,accounts,new FakeGamma(await fixture()));await crashed.initialize();await assert.rejects(crashed.settleFromPublicGamma(market,true),/terminal append failure/u);assert.equal(outbox.records.length,1);assert.equal((await first.service.detail(accounts.J_FEE_AWARE)).settlements.length,1);const restored=await paper(state);const recovered=new OfficialGammaPaperSettlementCoordinator(restored.service,outbox,accounts,new FakeGamma(await fixture()));await recovered.initialize();assert.equal(recovered.links()[0]?.state,"APPLIED");assert.equal(outbox.records.length,2);assert.equal((await restored.service.detail(accounts.K_DUAL_VOL)).settlements.length,1);});

test("a prior manual Paper result cannot masquerade as the official automatic settlement",async()=>{const {service}=await paper();await service.settleMarket(accounts.J_FEE_AWARE,market.marketId,"YES","2026-07-17T00:05:10.000Z");const outbox=new InMemoryOfficialPaperSettlementStore();const coordinator=new OfficialGammaPaperSettlementCoordinator(service,outbox,accounts,new FakeGamma(await fixture()));await coordinator.initialize();await assert.rejects(coordinator.settleFromPublicGamma(market,true),/cannot masquerade/u);assert.equal(outbox.records.length,1);assert.equal(outbox.records[0]?.link.state,"PENDING");assert.equal((await service.detail(accounts.K_DUAL_VOL)).settlements.length,0);});

test("hash tampering and a conflicting later winner are rejected",async()=>{const {service}=await paper();const store=new InMemoryOfficialPaperSettlementStore();const coordinator=new OfficialGammaPaperSettlementCoordinator(service,store,accounts,new FakeGamma(await fixture()));await coordinator.initialize();await coordinator.settleFromPublicGamma(market,true);const tampered=new InMemoryOfficialPaperSettlementStore();tampered.records.push(...structuredClone(store.records));tampered.records[0]={...tampered.records[0]!,link:{...tampered.records[0]!.link,winningToken:"NO"}};await assert.rejects(new OfficialGammaPaperSettlementCoordinator(service,tampered,accounts).initialize(),/hash mismatch/u);const raw=JSON.parse(await fixture()) as Record<string,unknown>;await assert.rejects(coordinator.applyGamma({expectedMarket:market,responseStatus:200,rawPayload:JSON.stringify({...raw,outcomePrices:'["0", "1"]'}),receiveTime}),/conflicts with the recorded/u);});
