import { useEffect, useState } from "react";
import { useWorkbenchCommands } from "../app/WorkbenchCommandContext.js";
import { useWorkbench } from "../app/WorkbenchContext.js";
import { useWorkbenchData } from "../app/WorkbenchDataContext.js";
import { DecisionTable } from "../components/DecisionTable.js";
import { LineChart } from "../components/LineChart.js";
import { Badge, EmptyState, PageHeader, Panel } from "../components/ui.js";

import type { BacktestJobV1, BacktestRequestV1, BacktestResultV1, DatasetListItemV1, StrategyDefinitionV1 } from "../services/workbench-commands.js";

export function BacktestPage() {
  const commands = useWorkbenchCommands();
  const { state: workbenchState } = useWorkbench();
  const { sourceKind, chartSeries, decisions, refresh: refreshWorkbench } = useWorkbenchData();
  const [request, setRequest] = useState<BacktestRequestV1>({ schemaVersion: "backtest-request-v1", requestId: `request-${Date.now()}`, strategyId: "", strategyVersion: "", datasetId: "", datasetVersionHash: "", feeModel: "fee-v2", latencyMs: 1000, initialCash: "1000", maxPosition: "100" }); const [definitions, setDefinitions] = useState<readonly StrategyDefinitionV1[]>([]); const [versions, setVersions] = useState<readonly string[]>([]); const [datasets, setDatasets] = useState<readonly DatasetListItemV1[]>([]); const [jobs,setJobs]=useState<readonly BacktestJobV1[]>([]); const [job, setJob] = useState<BacktestJobV1 | null>(null); const [result, setResult] = useState<BacktestResultV1 | null>(null); const [message, setMessage] = useState(commands === null ? "本地命令桥接不可用，回测启动已安全禁用" : "正在从后端加载策略与数据集…"); const [busy, setBusy] = useState(false);
  useEffect(() => { if (commands === null) return; let active = true; Promise.all([commands.listStrategyDefinitions(), commands.listDatasets(),commands.listBacktestJobs()]).then(async ([nextDefinitions, nextDatasets,nextJobs]) => { if (!active) return; setDefinitions(nextDefinitions); setDatasets(nextDatasets.datasets);setJobs(nextJobs); const requested = workbenchState.selectedStrategyId; const strategy = nextDefinitions.find((item) => item.strategyId === requested) ?? nextDefinitions[0]; const dataset = nextDatasets.datasets[0]; const nextVersions = strategy === undefined ? [] : await commands.listStrategyVersions(strategy.strategyId); if (!active) return; const requestedVersion = workbenchState.selectedStrategyVersion; const selectedVersion = requestedVersion !== null && nextVersions.includes(requestedVersion) ? requestedVersion : nextVersions[0] ?? ""; setVersions(nextVersions); setRequest((current) => ({ ...current, strategyId: strategy?.strategyId ?? "", strategyVersion: selectedVersion, datasetId: dataset?.datasetId ?? "", datasetVersionHash: dataset?.versionHash ?? "" })); setMessage(strategy === undefined || dataset === undefined || nextVersions.length === 0 ? "请先保存策略版本并发布可验证的数据集" : "已加载后端策略版本、数据集与任务历史，可运行回测"); }).catch((error: unknown) => { if (active) setMessage(error instanceof Error ? error.message : "回测配置加载失败"); }); return () => { active = false; }; }, [commands, workbenchState.selectedStrategyId, workbenchState.selectedStrategyVersion]);
  useEffect(()=>{if(commands===null||job===null||!(job.status==="queued"||job.status==="running"||job.status==="stopping"))return;let active=true;const timer=window.setInterval(()=>{commands.getBacktestJob(job.runId).then(async(next)=>{if(!active)return;setJob(next);setJobs(await commands.listBacktestJobs());if(next.status==="succeeded")await loadResult(next.runId);else setMessage(`任务状态：${next.status} · ${next.progressPermille/10}%`);}).catch((error:unknown)=>{if(active)setMessage(error instanceof Error?error.message:"任务轮询失败");});},1000);return()=>{active=false;window.clearInterval(timer);};},[commands,job?.runId,job?.status]);
  async function selectStrategy(strategyId: string) { field("strategyId", strategyId); if (commands === null) return; const next = await commands.listStrategyVersions(strategyId); setVersions(next); field("strategyVersion", next[0] ?? ""); }
  function selectDataset(value: string) { const dataset = datasets.find((item) => `${item.datasetId}:${item.versionHash}` === value); if (dataset !== undefined) setRequest((current) => ({ ...current, datasetId: dataset.datasetId, datasetVersionHash: dataset.versionHash })); }
  function field<K extends keyof BacktestRequestV1>(key: K, value: BacktestRequestV1[K]) { setRequest((current) => ({ ...current, [key]: value })); }
  async function loadResult(runId: string) { if (commands === null) return; const nextResult = await commands.getBacktestResult(runId); setResult(nextResult); await refreshWorkbench(); setMessage(`已加载后端回测结果 ${nextResult.runId}`); }
  async function start() { if (commands === null) return; setBusy(true); setResult(null); try { const next = await commands.startBacktest(request); setJob(next); setJobs(await commands.listBacktestJobs()); setMessage(`后端已接受任务 ${next.runId}`); if (next.status === "succeeded") await loadResult(next.runId); } catch (error) { setMessage(error instanceof Error ? error.message : "回测启动失败"); } finally { setBusy(false); } }
  async function refresh() { if (commands === null || job === null) return; setBusy(true); try { const next = await commands.getBacktestJob(job.runId); setJob(next); setMessage(`任务状态：${next.status} · ${next.progressPermille / 10}%`); if (next.status === "succeeded") await loadResult(next.runId); } catch (error) { setMessage(error instanceof Error ? error.message : "状态查询失败"); } finally { setBusy(false); } }
  async function stop() { if (commands === null || job === null) return; setBusy(true); try { const next = await commands.stopBacktest(job.runId); setJob(next); setMessage(`停止请求已提交：${next.status}`); } catch (error) { setMessage(error instanceof Error ? error.message : "停止失败"); } finally { setBusy(false); } }
  const runnable = commands !== null && request.strategyId !== "" && request.strategyVersion !== "" && request.datasetId !== "" && request.datasetVersionHash !== "";
  return <><PageHeader title="回测实验室（Backtest Lab）" subtitle="回测创建、状态与停止均经后端命令；历史原始数据不会进入前端。" action={<div className="toolbar"><button className="button" disabled={commands === null || job === null || busy} onClick={() => void refresh()}>刷新状态</button><button className="button" disabled={commands === null || job === null || busy || !["queued", "running"].includes(job.status)} onClick={() => void stop()}>停止任务</button><button className="button button--primary" disabled={!runnable || busy} onClick={() => void start()}>运行回测</button></div>} />
    <Panel title="新建模拟回测" english="Create Paper Backtest" action={<Badge tone={job?.status === "failed" ? "bad" : job === null ? "info" : "good"}>{job === null ? "NOT STARTED" : `${job.status.toUpperCase()} · ${job.progressPermille / 10}%`}</Badge>}><div className="form-grid"><label>请求 ID<input aria-label="回测请求 ID" value={request.requestId} onChange={(event) => field("requestId", event.target.value)} /></label><label>策略 ID<select aria-label="回测策略 ID" value={request.strategyId} onChange={(event) => void selectStrategy(event.target.value)}><option value="">请选择</option>{definitions.map((item) => <option key={item.strategyId} value={item.strategyId}>{item.displayName}</option>)}</select></label><label>策略版本<select aria-label="回测策略版本" value={request.strategyVersion} onChange={(event) => field("strategyVersion", event.target.value)}><option value="">请选择</option>{versions.map((version) => <option key={version}>{version}</option>)}</select></label><label className="field-wide">数据集<select aria-label="回测数据集" value={request.datasetId === "" ? "" : `${request.datasetId}:${request.datasetVersionHash}`} onChange={(event) => selectDataset(event.target.value)}><option value="">请选择后端已验证版本</option>{datasets.map((item) => <option key={`${item.datasetId}:${item.versionHash}`} value={`${item.datasetId}:${item.versionHash}`}>{item.datasetId} · {item.versionHash.slice(0, 12)}</option>)}</select></label><label>手续费模型<input aria-label="手续费模型" value={request.feeModel} readOnly /></label><label>执行延迟（毫秒）<input aria-label="延迟毫秒" type="number" min="1000" max="1000" value={request.latencyMs} readOnly /><small>当前已验证历史盘口只有 1 秒执行层，因此固定为 1000 ms；不会伪造亚秒成交。</small></label><label>初始资金<input aria-label="初始资金" value={request.initialCash} onChange={(event) => field("initialCash", event.target.value)} /></label><label>最大仓位<input aria-label="最大仓位" value={request.maxPosition} onChange={(event) => field("maxPosition", event.target.value)} /></label></div><pre className="console strategy-log" role="status">{message}</pre></Panel><Panel title="回测任务历史" english="Persisted Backtest Jobs">{jobs.length===0?<EmptyState title="尚无后端回测任务" detail="创建任务后会持久化并显示在这里。"/>:<table className="data-table"><thead><tr><th>运行</th><th>请求</th><th>状态</th><th>进度</th><th>操作</th></tr></thead><tbody>{jobs.map((item)=><tr key={item.runId}><td>{item.runId}</td><td>{item.requestId}</td><td>{item.status}</td><td>{item.progressPermille/10}%</td><td><button className="button" onClick={()=>{setJob(item);if(item.status==="succeeded")void loadResult(item.runId);}}>选择</button></td></tr>)}</tbody></table>}</Panel>
    {sourceKind === "preview" ? <><div className="backtest-summary"><Panel title="运行元数据" english="Run Metadata" action={<Badge tone="good">COMPLETE 完成</Badge>}><div className="metadata-grid"><span>运行 ID<b>BT-20260718-0042</b></span><span>策略<b>K-Edge v0.4</b></span><span>数据集<b>BTC5M-L2-v2</b></span><span>时间区间<b>06-01 → 07-15</b></span><span>Git 提交<b>73c0b8d</b></span><span>配置哈希<b>e41a2c9</b></span></div></Panel><div className="backtest-kpis"><MiniKpi label="净盈亏" value="+214.80" tone="positive"/><MiniKpi label="毛盈亏" value="+278.61"/><MiniKpi label="手续费" value="−63.81" tone="negative"/><MiniKpi label="最大回撤" value="−41.70" tone="negative"/><MiniKpi label="成交笔数" value="286"/><MiniKpi label="成交率" value="71.5%"/><MiniKpi label="胜率" value="58.7%"/><MiniKpi label="平均每笔" value="+0.75" tone="positive"/><MiniKpi label="Brier @ T−60s" value="0.0941"/><MiniKpi label="Log Loss" value="0.318"/><MiniKpi label="可估市场" value="412"/><MiniKpi label="未验证市场" value="37" tone="amber"/></div></div>
    <div className="backtest-chart-grid"><Panel title="累计净盈亏与回撤" english="Cumulative Net PnL & Drawdown"><LineChart series={[{label:"累计净盈亏",values:chartSeries.pnl,color:"#4fd17d"},{label:"回撤",values:chartSeries.pnl.map((value,index)=>value-Math.max(...chartSeries.pnl.slice(0,index+1))),color:"#ff676f"}]} /></Panel><Panel title="概率校准图" english="Reliability Diagram"><LineChart series={[{label:"实际频率",values:[6,16,27,42,50,64,75,79,90],color:"#4f91ff"},{label:"理想校准",values:[8,18,29,39,51,61,72,83,92],color:"#71818d"}]} /></Panel></div>
    <div className="backtest-lower"><Panel title="滚动布里尔分数" english="Rolling Brier Score"><LineChart height={230} series={[{label:"Brier",values:chartSeries.brier,color:"#4f91ff"}]} /></Panel><Panel title="分组表现" english="Grouped Performance"><div className="bar-list">{[["0–0.25%","−8.4",18,"negative"],["0.25–0.5%","+21.7",42,"positive"],["0.5–1.0%","+76.2",68,"positive"],["1.0–2.0%","+102.1",88,"positive"],[">2.0%","+23.2",36,"positive"]].map(([label,value,width,tone])=><div key={String(label)}><span>{label}</span><i><b style={{width:`${width}%`}} /></i><strong className={String(tone)}>{value}</strong></div>)}</div></Panel></div>
    <Panel title="回测决策账本" english="Backtest Decision Ledger"><DecisionTable rows={decisions} /></Panel></> : result === null ? <Panel title="回测结果" english="Backtest Result"><EmptyState title="尚无真实回测结果" detail={job === null ? "创建后端回测任务后，结果将在任务成功完成并通过 DTO 校验后显示。" : `任务 ${job.runId} 当前状态为 ${job.status}。`} /></Panel> : <VerifiedBacktestResult result={result} />}
  </>;
}

function MiniKpi({label,value,tone=""}:{label:string;value:string;tone?:string}){return <article><span>{label}</span><strong className={tone}>{value}</strong></article>}

function VerifiedBacktestResult({ result }: { result: BacktestResultV1 }) {
  const equity = result.equityCurve.map((point) => Number(point.equity)).filter(Number.isFinite);
  return <><div className="backtest-summary"><Panel title="运行元数据" english="Run Metadata" action={<Badge tone="good">COMPLETE 完成</Badge>}><div className="metadata-grid"><span>运行 ID<b>{result.runId}</b></span><span>策略<b>{result.request.strategyId} v{result.request.strategyVersion}</b></span><span>数据集<b>{result.request.datasetId}</b></span><span>开始时间<b>{result.startedAtUtc}</b></span><span>完成时间<b>{result.completedAtUtc}</b></span><span>事件数<b>{result.events.length}</b></span></div></Panel><div className="backtest-kpis"><MiniKpi label="净盈亏" value={result.metrics.netPnl} /><MiniKpi label="手续费" value={result.metrics.fees} /><MiniKpi label="最大回撤" value={result.metrics.maxDrawdown} /><MiniKpi label="成交率" value={result.metrics.fillRate} /><MiniKpi label="胜率" value={result.metrics.winRate} /><MiniKpi label="Brier" value={result.metrics.brier ?? "不可用"} /></div></div><Panel title="资金曲线" english="Equity Curve">{equity.length > 1 ? <LineChart series={[{ label: "equity", values: equity, color: "#4fd17d" }]} /> : <EmptyState title="资金曲线不可用" detail="后端结果未包含足够的资金曲线点。" />}</Panel><Panel title="回测事件" english="Backtest Events">{result.events.length === 0 ? <EmptyState title="没有回测事件" detail="后端结果未返回决策、订单、成交或结算事件。" /> : <table className="data-table"><thead><tr><th>时间</th><th>类型</th><th>事件 ID</th></tr></thead><tbody>{result.events.map((event) => <tr key={event.eventId}><td>{event.eventTimeUtc}</td><td>{event.kind}</td><td>{event.eventId}</td></tr>)}</tbody></table>}</Panel></>;
}
