import { useEffect, useState } from "react";

import { useWorkbenchCommands } from "../app/WorkbenchCommandContext.js";
import { useWorkbench } from "../app/WorkbenchContext.js";
import { EventComposition, ProbabilityEventTimeline } from "../components/QuantAnalysis.js";
import { Badge, EmptyState, eventFieldLabel, eventPrimaryMeaning, formatEventUtc, PageHeader, PaginationControls, Panel } from "../components/ui.js";
import type { BacktestJobV1, PaperReplayEventV1, PublicBacktestEventV1 } from "../services/workbench-commands.js";

export function ReplayPage() {
  const commands = useWorkbenchCommands();
  const { state, dispatch } = useWorkbench();
  const [source, setSource] = useState<"backtest" | "paper">("backtest");
  const [runs, setRuns] = useState<readonly BacktestJobV1[]>([]); const [runId, setRunId] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState<10 | 20 | 50>(20);
  const [replay, setReplay] = useState<Readonly<{ totalItems:number; totalPages:number; items:readonly (PublicBacktestEventV1|PaperReplayEventV1)[] }> | null>(null); const [index, setIndex] = useState(0); const [playing, setPlaying] = useState(false); const [speedMs, setSpeedMs] = useState(1000); const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState(commands === null ? "本地命令桥接不可用；市场回放保持关闭。" : "正在查询已完成的后端回测…");
  useEffect(() => { if (commands === null) return; let active = true; commands.listBacktestJobs().then((items) => { if (!active) return; const complete = items.filter((item) => item.status === "succeeded"); const requestedRun = state.researchSession.runId; setRuns(complete); setRunId(complete.some((item) => item.runId === requestedRun) ? requestedRun! : complete[0]?.runId ?? ""); setStatus(complete.length === 0 ? "没有可回放的完成运行。" : requestedRun ? "已从研究会话恢复运行与分析范围。" : `已找到 ${complete.length} 个完成运行。`); }).catch((error: unknown) => { if (active) setStatus(message(error, "完成运行查询失败；未显示预览回放。")); }); return () => { active = false; }; }, [commands]);
  useEffect(() => { if (commands === null || (source === "backtest" && runId === "")) { setReplay(null); return; } let active = true; setBusy(true); setPlaying(false); setReplay(null); const query = source === "paper" ? commands.getPaperReplay({ page, pageSize }) : commands.getBacktestReplay(runId, { page, pageSize }); query.then((value) => { if (active) { setReplay({ totalItems:value.totalItems, totalPages:value.totalPages, items: [...value.items].sort((a, b) => a.eventTimeUtc.localeCompare(b.eventTimeUtc) || a.eventId.localeCompare(b.eventId)) }); setIndex(0); setStatus(source === "paper" ? `已加载持久 Paper 第 ${page} 页回放事件。` : `已加载所选运行第 ${page} 页回放事件。`); } }).catch((error: unknown) => { if (active) setStatus(message(error, "回放查询失败；未显示预览事件。")); }).finally(() => { if (active) setBusy(false); }); return () => { active = false; }; }, [commands, runId, page, pageSize, source]);
  useEffect(() => { if (!playing || replay === null || replay.items.length < 2) return; const timer = window.setInterval(() => setIndex((value) => { if (value >= replay.items.length - 1) { setPlaying(false); return value; } return value + 1; }), speedMs); return () => window.clearInterval(timer); }, [playing, replay, speedMs]);
  const current = replay?.items[index]; const totalPages = replay?.totalPages ?? 0; const selectedRun = runs.find((run) => run.runId === runId);
  return <><PageHeader title="运行回放（Market Replay · 市场回放）" subtitle="回答“过程怎样发生”：按后端冻结时间顺序重演市场、判断、模拟订单、成交与结算。" />
    <section className="page-purpose page-purpose--replay" aria-label="运行回放用途">
      <span>REPLAY · PROCESS</span><strong>同一事件证据的时间播放器</strong><p>按冻结时间逐条播放，定位某个判断前后发生了什么；决策账本使用同一后端事件源，但负责筛选、分页核对和技术审计。</p>
    </section>
    <Panel title="回放来源" english="Backend Replay Source"><div className="toolbar"><label>来源 <select aria-label="回放来源" value={source} onChange={(event) => { setPage(1); setSource(event.target.value as "backtest"|"paper"); }}><option value="backtest">历史回测</option><option value="paper">实时 Paper / KJ</option></select></label>{source === "backtest" ? <label>已完成运行 <select aria-label="回放运行" value={runId} disabled={busy || commands === null} onChange={(event) => { setPage(1); setRunId(event.target.value); dispatch({ type: "update-research-session", patch: { runId: event.target.value || null, stage: "analysis" } }); }}><option value="">请选择</option>{runs.map((run) => <option key={run.runId} value={run.runId}>{run.displayName ?? "历史运行（未记录名称）"}</option>)}</select></label> : null}</div><PaginationControls label="运行回放" page={page} totalPages={totalPages} pageSize={pageSize} totalItems={replay?.totalItems ?? 0} busy={busy} onPageChange={setPage} onPageSizeChange={(value) => { setPage(1); setPageSize(value); }} />{selectedRun === undefined ? null : <div className="panel-note">{selectedRun.displayName ?? "历史运行（未记录名称）"}<details className="technical-details"><summary>查看运行 ID</summary>{selectedRun.runId}</details></div>}<p role="status">{status}</p></Panel>
    {source === "backtest" && runId === "" ? <Panel title="回放事件" english="Replay Events"><EmptyState title="没有可回放的完成运行" detail="先通过后端完成一次回测；这里不会使用演示事件代替。" /></Panel> : replay === null ? <Panel title="回放事件" english="Replay Events"><EmptyState title={busy ? "正在加载后端回放" : "后端回放不可用"} detail={status} /></Panel> : current === undefined ? <Panel title="回放事件" english="Replay Events"><EmptyState title="本页没有回放事件" detail="后端未返回本页冻结事件。" /></Panel> : <>
      <div className="replay-analysis-grid"><Panel title="决策概率轨迹" english="Decision Probability · UTC"><ProbabilityEventTimeline events={replay.items} /></Panel><Panel title="本页事件构成" english="Event Composition"><EventComposition events={replay.items} /><div className="coverage-kpis"><span>事件总数<b>{replay.items.length}</b></span><span>决策<b>{replay.items.filter((event) => event.kind === "decision").length}</b></span><span>成交<b>{replay.items.filter((event) => event.kind === "fill").length}</b></span><span>结算<b>{replay.items.filter((event) => event.kind === "settlement").length}</b></span></div></Panel></div>
      <Panel title="回放控制" english="Replay Controls"><div className="replay-controls"><button className="button" disabled={index === 0} onClick={() => setIndex((value) => Math.max(0, value - 1))}>◀ 上一事件</button><button className="button button--primary" onClick={() => setPlaying((value) => !value)}>{playing ? "Ⅱ 暂停" : "▶ 播放"}</button><button className="button" disabled={index >= replay.items.length - 1} onClick={() => setIndex((value) => Math.min(replay.items.length - 1, value + 1))}>下一事件 ▶</button><label>速度 <select aria-label="回放速度" value={speedMs} onChange={(event) => setSpeedMs(Number(event.target.value))}><option value={2000}>0.5×</option><option value={1000}>1×</option><option value={200}>5×</option><option value={50}>20×</option></select></label><input className="timeline" aria-label="回放位置" type="range" min="0" max={Math.max(0, replay.items.length - 1)} value={index} onChange={(event) => { setPlaying(false); setIndex(Number(event.target.value)); }} /><strong>{index + 1} / {replay.items.length}</strong></div></Panel><div className="replay-grid"><Panel title="本页事件流" english="Page Event Stream"><div className="replay-event-table" tabIndex={0} aria-label="本页回放事件列表"><table className="data-table"><thead><tr><th>#</th><th>时间</th><th>类型</th><th>原因 / 状态</th><th>技术详情</th></tr></thead><tbody>{replay.items.map((event, eventIndex) => <tr className={eventIndex === index ? "selected" : ""} aria-current={eventIndex === index ? "true" : undefined} key={`${event.kind}:${event.eventId}`} onClick={() => { setPlaying(false); setIndex(eventIndex); }}><td>{(page - 1) * pageSize + eventIndex + 1}</td><td>{formatEventUtc(event.eventTimeUtc)}</td><td>{event.kind}</td><td>{eventPrimaryMeaning(event.data)}</td><td><details className="technical-details"><summary>查看事件 ID</summary>{event.eventId}</details></td></tr>)}</tbody></table></div></Panel><Panel title="当前后端事件" english="Current Backend Event"><div className="inspector replay-inspector"><Badge tone="info">{current.kind}</Badge><h3>{eventPrimaryMeaning(current.data)}</h3><dl><dt>事件时间</dt><dd>{formatEventUtc(current.eventTimeUtc)}</dd>{"source" in current ? <><dt>来源</dt><dd>{current.source}</dd></> : null}{Object.entries(current.data).map(([key, value]) => <span key={key}><dt>{eventFieldLabel(key)}</dt><dd>{value === null ? "未记录" : String(value)}</dd></span>)}</dl><details className="technical-details"><summary>查看技术事件 ID</summary>{current.eventId}</details></div></Panel></div></>}
  </>;
}

function message(error: unknown, fallback: string): string { return error instanceof Error && error.message.trim() !== "" ? error.message : fallback; }
