import { useEffect, useState } from "react";
import { useWorkbench } from "../app/WorkbenchContext.js";
import { useWorkbenchCommands } from "../app/WorkbenchCommandContext.js";
import { Badge, PageHeader, Panel } from "../components/ui.js";
import type { StrategyDefinitionV1, StrategyParameterValue } from "../services/workbench-commands.js";

export function StrategyPage() {
  const commands = useWorkbenchCommands(); const { dispatch } = useWorkbench();
  const [definitions, setDefinitions] = useState<readonly StrategyDefinitionV1[]>([]); const [strategyId, setStrategyId] = useState(""); const [version, setVersion] = useState("1.0.0"); const [savedVersions, setSavedVersions] = useState<readonly string[]>([]); const [selectedVersion, setSelectedVersion] = useState(""); const [description, setDescription] = useState("可复现的 paper / 回测策略版本"); const [parameters, setParameters] = useState<Readonly<Record<string, StrategyParameterValue>>>({}); const [status, setStatus] = useState(commands === null ? "本地命令桥接不可用：验证与保存已安全禁用" : "正在加载后端策略注册表…"); const [busy, setBusy] = useState(false); const [valid, setValid] = useState<boolean | null>(null);
  useEffect(() => { if (commands === null) return; let active = true; commands.listStrategyDefinitions().then(async (items) => { if (!active) return; setDefinitions(items); const first = items[0]; if (first === undefined) { setStatus("后端未注册任何策略"); return; } const versions = await commands.listStrategyVersions(first.strategyId); if (!active) return; setStrategyId(first.strategyId); setParameters(defaultParameters(first)); setSavedVersions(versions); setSelectedVersion(versions[0] ?? ""); setStatus(`已从后端加载 ${items.length} 个策略定义和 ${versions.length} 个已保存版本`); }).catch((error: unknown) => { if (active) setStatus(error instanceof Error ? error.message : "策略注册表不可用"); }); return () => { active = false; }; }, [commands]);
  const definition = definitions.find((item) => item.strategyId === strategyId);
  async function selectStrategy(next: string) { setStrategyId(next); const selected = definitions.find((item) => item.strategyId === next); if (selected !== undefined) setParameters(defaultParameters(selected)); setSavedVersions([]); setSelectedVersion(""); setValid(null); if (commands === null || next === "") return; try { const versions = await commands.listStrategyVersions(next); setSavedVersions(versions); setSelectedVersion(versions[0] ?? ""); setStatus(`已加载 ${next} 的 ${versions.length} 个已保存版本`); } catch (error) { setStatus(error instanceof Error ? error.message : "版本列表加载失败"); } }
  function updateParameter(name: string, raw: string, type: "string" | "number" | "boolean") { setParameters((current) => ({ ...current, [name]: type === "number" ? Number(raw) : type === "boolean" ? raw === "true" : raw })); setValid(null); }
  async function validate() { if (commands === null || strategyId === "") return; setBusy(true); try { const result = await commands.validateStrategyParameters(strategyId, parameters); setValid(result.valid); setStatus(result.valid ? "后端参数校验通过" : `参数校验失败：${result.errors.join("；")}`); } catch (error) { setValid(false); setStatus(error instanceof Error ? error.message : "参数校验失败"); } finally { setBusy(false); } }
  async function save() { if (commands === null || strategyId === "") return; setBusy(true); try { const result = await commands.saveStrategyVersion({ schemaVersion: "strategy-version-v1", strategyId, version, description, parameters, createdAtUtc: new Date().toISOString() }); const versions = await commands.listStrategyVersions(strategyId); setSavedVersions(versions); setSelectedVersion(result.version); setValid(true); setStatus(`已由后端保存不可变版本 ${result.strategyId} v${result.version}`); } catch (error) { setStatus(error instanceof Error ? error.message : "保存失败"); } finally { setBusy(false); } }
  async function reload() { if (commands === null || strategyId === "" || selectedVersion === "") return; setBusy(true); try { const loaded = await commands.getStrategyVersion(strategyId, selectedVersion); setVersion(loaded.version); setDescription(loaded.description); setParameters(loaded.parameters); setValid(true); setStatus(`已从后端重新加载 ${loaded.strategyId} v${loaded.version}`); } catch (error) { setValid(false); setStatus(error instanceof Error ? error.message : "版本重新加载失败"); } finally { setBusy(false); } }
  function openBacktest() { if (strategyId === "" || selectedVersion === "") return; dispatch({ type: "select-strategy-version", strategyId, version: selectedVersion }); dispatch({ type: "navigate", routeId: "backtest" }); }
  return <><PageHeader title="策略工作室（Strategy Studio）" subtitle="新增实现由统一注册表接入；页面只负责参数校验、不可变版本和进入回测。" action={<div className="toolbar"><button className="button" disabled={commands === null || busy} onClick={() => void validate()}>验证参数</button><button className="button" disabled={commands === null || busy} onClick={() => void save()}>保存版本</button><button className="button button--primary" disabled={strategyId === "" || selectedVersion === ""} onClick={openBacktest}>运行回测</button></div>} />
    <div className="strategy-fidelity-grid">
      <Panel title="后端策略契约（只读）" english="Registered Strategy Contract" action={<Badge tone={valid === false ? "bad" : valid === true ? "good" : "info"}>{valid === true ? "PARAMETERS VALID" : valid === false ? "PARAMETERS INVALID" : "BACKEND MANAGED"}</Badge>}><textarea className="code-editor code-editor--python" value={definition === undefined ? "等待后端策略定义" : JSON.stringify(definition, null, 2)} readOnly spellCheck={false} aria-label="后端策略契约（只读）" /><pre className="console strategy-log" role="status">{status}</pre></Panel>
      <div className="stack"><Panel title="策略身份与版本" action={<Badge tone="info">DRAFT 草稿</Badge>}><div className="form-grid"><label>策略 ID<select aria-label="策略 ID" value={strategyId} onChange={(event) => void selectStrategy(event.target.value)}><option value="">请选择后端策略</option>{definitions.map((item) => <option key={item.strategyId} value={item.strategyId}>{item.displayName} · {item.strategyId}</option>)}</select></label><label>版本<input aria-label="版本" value={version} onChange={(event) => setVersion(event.target.value)} /></label><label className="field-wide">说明<input aria-label="说明" value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>运行语言<input value={definition?.runtime ?? "不可用"} readOnly /></label><label>允许模式<input value={definition === undefined ? "不可用" : definition.allowedModes.join(" / ")} readOnly /></label><label>已保存版本<select aria-label="已保存策略版本" value={selectedVersion} onChange={(event) => setSelectedVersion(event.target.value)}><option value="">暂无已保存版本</option>{savedVersions.map((item) => <option key={item}>{item}</option>)}</select></label><label>版本操作<button className="button" disabled={commands === null || busy || selectedVersion === ""} onClick={() => void reload()}>重新加载版本</button></label></div></Panel>
        <Panel title="策略参数（Parameters）"><div className="form-grid">{definition === undefined ? <p className="empty-state">等待后端策略定义</p> : Object.entries(definition.parameters).map(([name, rule]) => <label key={name}>{name}<input aria-label={`参数 ${name}`} type={rule.type === "number" ? "number" : "text"} value={String(parameters[name] ?? "")} min={rule.minimum} max={rule.maximum} onChange={(event) => updateParameter(name, event.target.value, rule.type)} /></label>)}</div></Panel>
        <Panel title="数据与执行模型" english="Data & Execution Model"><p>数据集、手续费、延迟、仓位和成交模型在“回测实验室”中选择，并由后端再次验证；策略版本不保存文件路径或数据库连接。</p></Panel>
        <Panel title="验证结果（Validation）"><div className="validation-list"><span>命令桥接 <b className={commands === null ? "negative" : "positive"}>{commands === null ? "不可用" : "可用"}</b></span><span>参数 Schema <b className={valid === false ? "negative" : valid === true ? "positive" : "amber"}>{valid === true ? "通过" : valid === false ? "失败" : "待验证"}</b></span><span>历史表现 <b className="amber">需运行回测</b></span><span>盈利能力 <b className="amber">未证明</b></span><span>真实交易 <b className="positive">禁用</b></span><span>持久化所有者 <b className="positive">后端</b></span></div></Panel></div>
    </div>
  </>;
}

function defaultParameters(definition: StrategyDefinitionV1): Readonly<Record<string, StrategyParameterValue>> { return Object.fromEntries(Object.entries(definition.parameters).map(([name, rule]) => [name, rule.type === "number" ? rule.minimum ?? 0 : rule.type === "boolean" ? false : ""])); }
