import { useEffect, useState } from "react";
import { useWorkbench } from "../app/WorkbenchContext.js";
import { useWorkbenchCommands } from "../app/WorkbenchCommandContext.js";
import { Badge, formatUtc, PageHeader, Panel } from "../components/ui.js";
import type { StrategyDefinitionV1, StrategyParameterValue, StrategyValidationWarningV1, StrategyVersionV1 } from "../services/workbench-commands.js";

export function StrategyPage() {
  const commands = useWorkbenchCommands(); const { dispatch } = useWorkbench();
  const [definitions, setDefinitions] = useState<readonly StrategyDefinitionV1[]>([]); const [strategyId, setStrategyId] = useState(""); const [version, setVersion] = useState("1.0.0"); const [savedVersions, setSavedVersions] = useState<readonly string[]>([]); const [versionRecords, setVersionRecords] = useState<readonly StrategyVersionV1[]>([]); const [selectedVersion, setSelectedVersion] = useState(""); const [description, setDescription] = useState("可复现的 paper / 回测策略版本"); const [createdAtUtc, setCreatedAtUtc] = useState<string | null>(null); const [parameters, setParameters] = useState<Readonly<Record<string, StrategyParameterValue>>>({}); const [status, setStatus] = useState(commands === null ? "本地命令桥接不可用：验证与保存已安全禁用" : "正在加载后端策略注册表…"); const [busy, setBusy] = useState(false); const [valid, setValid] = useState<boolean | null>(null); const [warnings, setWarnings] = useState<readonly StrategyValidationWarningV1[]>([]);
  useEffect(() => { if (commands === null) return; let active = true; commands.listStrategyDefinitions().then(async (items) => { if (!active) return; setDefinitions(items); const first = items[0]; if (first === undefined) { setStatus("后端未注册任何策略"); return; } const versions = await commands.listStrategyVersions(first.strategyId); const records = await Promise.all(versions.map((item) => commands.getStrategyVersion(first.strategyId, item))); if (!active) return; setStrategyId(first.strategyId); setParameters(defaultParameters(first)); setSavedVersions(versions); setVersionRecords(records); setSelectedVersion(versions.at(-1) ?? ""); setVersion(nextPatchVersion(versions)); setStatus(`已从后端加载 ${items.length} 个策略定义和 ${versions.length} 个已保存版本`); }).catch((error: unknown) => { if (active) setStatus(error instanceof Error ? error.message : "策略注册表不可用"); }); return () => { active = false; }; }, [commands]);
  const definition = definitions.find((item) => item.strategyId === strategyId);
  async function selectStrategy(next: string) { setStrategyId(next); const selected = definitions.find((item) => item.strategyId === next); if (selected !== undefined) setParameters(defaultParameters(selected)); setSavedVersions([]); setVersionRecords([]); setSelectedVersion(""); setCreatedAtUtc(null); setValid(null); if (commands === null || next === "") return; try { const versions = await commands.listStrategyVersions(next); const records = await Promise.all(versions.map((item) => commands.getStrategyVersion(next, item))); setSavedVersions(versions); setVersionRecords(records); setSelectedVersion(versions.at(-1) ?? ""); setVersion(nextPatchVersion(versions)); setStatus(`已加载 ${selected?.displayName ?? next} 的 ${versions.length} 个已保存版本；可在版本差异中查看逐参数变化`); } catch (error) { setStatus(error instanceof Error ? error.message : "版本列表加载失败"); } }
  function updateParameter(name: string, raw: string, type: "string" | "number" | "boolean") { setParameters((current) => ({ ...current, [name]: type === "number" ? Number(raw) : type === "boolean" ? raw === "true" : raw })); setValid(null); setWarnings([]); }
  async function validate() { if (commands === null || strategyId === "") return; setBusy(true); try { const result = await commands.validateStrategyParameters(strategyId, parameters); setValid(result.valid); setWarnings(result.warnings); setStatus(result.valid ? result.warnings.length === 0 ? "后端参数校验通过" : `后端参数校验通过，但有 ${result.warnings.length} 条研究告警` : `参数校验失败：${result.errors.join("；")}`); } catch (error) { setValid(false); setWarnings([]); setStatus(error instanceof Error ? error.message : "参数校验失败"); } finally { setBusy(false); } }
  async function save() { if (commands === null || strategyId === "") return; setBusy(true); try { const result = await commands.saveStrategyVersion({ schemaVersion: "strategy-version-v1", strategyId, version, description, parameters, createdAtUtc: new Date().toISOString() }); const versions = await commands.listStrategyVersions(strategyId); const records = await Promise.all(versions.map((item) => commands.getStrategyVersion(strategyId, item))); setSavedVersions(versions); setVersionRecords(records); setSelectedVersion(result.version); setVersion(nextPatchVersion(versions)); setCreatedAtUtc(result.createdAtUtc); setValid(true); setStatus(`已由后端保存不可变版本 ${result.strategyId} v${result.version}；下一个版本号已准备好`); } catch (error) { setStatus(error instanceof Error ? error.message : "保存失败"); } finally { setBusy(false); } }
  async function reload() { if (commands === null || strategyId === "" || selectedVersion === "") return; setBusy(true); try { const loaded = await commands.getStrategyVersion(strategyId, selectedVersion); setVersion(nextPatchVersion(savedVersions)); setDescription(loaded.description); setParameters(loaded.parameters); setCreatedAtUtc(loaded.createdAtUtc); setValid(true); setStatus(`已从后端重新加载 ${loaded.strategyId} v${loaded.version} 的参数；新版本号已准备好`); } catch (error) { setValid(false); setStatus(error instanceof Error ? error.message : "版本重新加载失败"); } finally { setBusy(false); } }
  async function deleteVersion(){if(commands===null||strategyId===""||selectedVersion===""||!window.confirm(`删除策略版本？\n\n${strategyId} v${selectedVersion}\n\n已被回测引用的版本不会被删除。`))return;setBusy(true);try{await commands.deleteStrategyVersion(strategyId,selectedVersion);const versions=await commands.listStrategyVersions(strategyId);const records=await Promise.all(versions.map((item)=>commands.getStrategyVersion(strategyId,item)));setSavedVersions(versions);setVersionRecords(records);setSelectedVersion(versions.at(-1)??"");setCreatedAtUtc(null);setStatus(`已删除策略版本 ${strategyId} v${selectedVersion}`);}catch(error){setStatus(error instanceof Error?error.message:"策略版本删除失败");}finally{setBusy(false);}}
  function openBacktest() { if (strategyId === "" || selectedVersion === "" || definition?.allowedModes.includes("backtest") !== true) return; dispatch({ type: "select-strategy-version", strategyId, version: selectedVersion }); dispatch({ type: "navigate", routeId: "backtest" }); }
  const gateFailed = definition?.researchStatus === "RESEARCH_GATE_FAILED";
  const selectedRecord = versionRecords.find((item) => item.version === selectedVersion) ?? null;
  const priorRecord = selectedRecord === null ? null : versionRecords[versionRecords.findIndex((item) => item.version === selectedVersion) - 1] ?? null;
  return <><PageHeader title="策略工作室（Strategy Studio）" subtitle="先选择策略和版本，再调整参数；技术契约收在页面末尾。" action={<div className="toolbar"><button className="button" disabled={commands === null || busy || gateFailed} onClick={() => void validate()}>验证参数</button><button className="button" disabled={commands === null || busy || gateFailed} onClick={() => void save()}>保存版本</button><button className="button button--primary" disabled={strategyId === "" || selectedVersion === "" || definition?.allowedModes.includes("backtest") !== true} onClick={openBacktest}>使用此版本回测</button></div>} />
    <section className="selection-hero" aria-label="当前策略摘要"><div><span className="eyebrow">当前策略</span><h2>{definition?.displayName ?? "请选择策略"}</h2><p>{definition?.summary ?? "从后端注册表选择一个策略后查看用途和约束。"}</p></div><div className="selection-hero__facts"><span>策略家族<b>{definition?.family ?? "未记录"}</b></span><span>研究状态<b>{definition === undefined ? "—" : gateFailed ? "历史门失败" : definition.researchStatus === "RESEARCH_ONLY" || !definition.allowedModes.includes("paper") ? "仅研究" : "可用于 Paper"}</b></span><span>风险等级<b>{definition?.riskLevel ?? "未记录"}</b></span><span>当前版本<b>{selectedVersion || "未保存"}</b></span><span>生成时间<b title={createdAtUtc ?? undefined}>{formatUtc(createdAtUtc)}</b></span></div></section>
    <div className="workflow-grid workflow-grid--strategy">
      <div className="stack"><Panel title="1. 选择策略与版本" action={<Badge tone={gateFailed ? "bad" : definition?.researchStatus === "RESEARCH_ONLY" || (definition !== undefined && !definition.allowedModes.includes("paper")) ? "warn" : "info"}>{gateFailed ? "HISTORICAL · LOCKED" : definition?.researchStatus === "RESEARCH_ONLY" || (definition !== undefined && !definition.allowedModes.includes("paper")) ? "RESEARCH ONLY" : "BACKEND MANAGED"}</Badge>}><div className="adaptive-form"><label className="field-span-6">策略<select aria-label="策略 ID" value={strategyId} onChange={(event) => void selectStrategy(event.target.value)}><option value="">请选择后端策略</option>{definitions.map((item) => <option key={item.strategyId} value={item.strategyId}>{item.displayName}</option>)}</select><small>名称优先显示；内部 ID 仅用于追溯</small></label><label className="field-span-3">新版本号<input aria-label="版本" value={version} onChange={(event) => setVersion(event.target.value)} /></label><label className="field-span-3">已保存版本<select aria-label="已保存策略版本" value={selectedVersion} onChange={(event) => { setSelectedVersion(event.target.value); setCreatedAtUtc(null); }}><option value="">暂无已保存版本</option>{savedVersions.map((item) => <option key={item}>{item}</option>)}</select></label><label className="field-span-9">版本说明<input aria-label="说明" value={description} onChange={(event) => setDescription(event.target.value)} /></label><div className="field-span-3 form-actions"><button className="button" disabled={commands === null || busy || selectedVersion === ""} onClick={() => void reload()}>加载版本</button><button className="button button--danger" disabled={commands===null||busy||selectedVersion===""||gateFailed} onClick={()=>void deleteVersion()}>删除版本</button></div></div></Panel>
        <Panel title="版本差异" english="Version Difference"><div className="validation-list"><span>所选版本 <b>{selectedRecord?.version ?? "未保存"}</b></span><span>创建时间 <b>{formatUtc(selectedRecord?.createdAtUtc)}</b></span><span>对比基线 <b>{priorRecord?.version ?? "无更早版本"}</b></span><span>版本说明 <b>{selectedRecord?.description ?? "未记录"}</b></span></div>{selectedRecord === null ? <p className="panel-note">先加载一个已保存版本，才能比较其与上一版本的参数差异。</p> : <div className="table-scroll"><table className="data-table"><thead><tr><th>参数</th><th>当前</th><th>{priorRecord === null ? "上一版本" : priorRecord.version}</th><th>变化</th></tr></thead><tbody>{Object.entries(selectedRecord.parameters).map(([name,value]) => { const before = priorRecord?.parameters[name]; const changed = before !== value; return <tr key={name}><td>{definition?.parameters[name]?.displayName ?? name}</td><td>{String(value)}</td><td>{before === undefined ? "—" : String(before)}</td><td className={changed ? "amber" : ""}>{changed ? "已变更" : "相同"}</td></tr>; })}</tbody></table></div>}</Panel>
        <Panel title="2. 策略参数" english="Parameters"><div className="adaptive-form">{definition === undefined ? <p className="empty-state field-span-12">等待后端策略定义</p> : Object.entries(definition.parameters).map(([name, rule]) => <label className="field-span-3 parameter-field" key={name}><span>{rule.displayName ?? name}{rule.unit && <em>{rule.unit}</em>}</span><input aria-label={`参数 ${name}`} title={rule.description} type={rule.type === "number" ? "number" : "text"} value={String(parameters[name] ?? "")} min={rule.minimum} max={rule.maximum} onChange={(event) => updateParameter(name, event.target.value, rule.type)} /><small>{rule.description ?? name}</small></label>)}</div></Panel></div>
      <div className="stack"><Panel title="验证与使用边界" action={<Badge tone={valid === false ? "bad" : warnings.some((warning) => warning.severity === "danger") ? "bad" : valid === true ? "good" : "warn"}>{valid === true ? warnings.length === 0 ? "已验证" : "已验证 · 有告警" : valid === false ? "验证失败" : "待验证"}</Badge>}><div className="validation-list"><span>参数 Schema <b className={valid === false ? "negative" : valid === true ? "positive" : "amber"}>{valid === true ? "通过" : valid === false ? "失败" : "待验证"}</b></span><span>允许模式 <b>{definition === undefined ? "不可用" : definition.allowedModes.join(" / ")}</b></span><span>盈利能力 <b className="amber">未证明</b></span><span>真实交易 <b className="positive">禁用</b></span></div>{warnings.length === 0 ? null : <div className="validation-list" aria-label="研究告警">{warnings.map((warning) => <span key={warning.code}>研究告警 <b className={warning.severity === "danger" ? "negative" : "amber"}>{warning.message}</b></span>)}</div>}<pre className="console strategy-log" role="status">{status}</pre></Panel><Panel title="数据与执行模型"><p>数据集、手续费、延迟、仓位和成交模型在回测实验室中选择，并由后端再次验证。</p></Panel></div>
    </div>
    <details className="technical-details"><summary>技术详情与后端策略契约</summary><div className="technical-details__body"><dl className="compact-dl"><dt>策略 ID</dt><dd>{strategyId || "—"}</dd><dt>运行语言</dt><dd>{definition?.runtime ?? "—"}</dd></dl><label className="sr-only">允许模式<input aria-label="允许模式" value={definition === undefined ? "不可用" : definition.allowedModes.join(" / ")} readOnly /></label><textarea className="code-editor" value={definition === undefined ? "等待后端策略定义" : JSON.stringify(definition, null, 2)} readOnly spellCheck={false} aria-label="后端策略契约（只读）" /></div></details>
  </>;
}

function defaultParameters(definition: StrategyDefinitionV1): Readonly<Record<string, StrategyParameterValue>> { return Object.fromEntries(Object.entries(definition.parameters).map(([name, rule]) => [name, rule.defaultValue ?? (rule.type === "number" ? rule.minimum ?? 0 : rule.type === "boolean" ? false : "")])); }
function nextPatchVersion(versions:readonly string[]):string{let best:[number,number,number]=[1,0,-1];for(const value of versions){const match=/^(\d+)\.(\d+)\.(\d+)$/u.exec(value);if(match===null)continue;const current:[number,number,number]=[Number(match[1]),Number(match[2]),Number(match[3])];if(current[0]>best[0]||(current[0]===best[0]&&current[1]>best[1])||(current[0]===best[0]&&current[1]===best[1]&&current[2]>best[2]))best=current;}return `${best[0]}.${best[1]}.${best[2]+1}`;}
